name: regru
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Copy api
        run: sudo cp -rf /home/runner/work/quasar-test/quasar-test/api /home/runner/work/quasar-test/quasar-test/dist/spa/

